### ISSUE TITLE
[pipewire] no audio

### ISSUE THREAD

**Issue by NoSequel** [git-bruh/kiss-repo#1]
Same issue as described in https://github.com/gkisslinux/kiss-bloat/issues/2 and https://github.com/kisslinux/repo/discussions/370

**Comment by git-bruh** [comment]
Hi, could you join the `#kisslinux` channel on `irc.libera.chat` ? Will be faster to discuss things there, since this seems to be a general issue as neither alsa nor pipewire work. I'm checking the kernel config you shared on the github discussion.

**Comment by NoSequel** [comment]
> Hi, could you join the `#kisslinux` channel on `irc.libera.chat` ? Will be faster to discuss things there, since this seems to be a general issue as neither alsa nor pipewire work. I'm checking the kernel config you shared on the github discussion.

yeah of course, getting an IRC client.
